apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80          # Port exposed externally
      targetPort: 80    # Port on your container
